# Generated by Django 5.1.6 on 2025-03-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pricelist_size_remove_product_discount_and_more'),
        ('orders', '0002_remove_order_postal_code_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.productsize'),
        ),
    ]
