# Generated by Django 5.1.6 on 2025-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
