# Generated by Django 5.1.6 on 2025-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Отменён'), ('waiting', 'В ожидании'), ('delivered', 'Доставлен')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
